"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Heart, Loader2, MessageCircle, Send, Share2, Sparkles, UsersRound } from "lucide-react";
import { getAuthUser, AuthUser } from "@/lib/auth";
import { Comment, CommunityPost, createComment, createPost, createReaction, deleteReaction, getComments, getCommunityPosts, getReactions } from "@/lib/social";

function timeAgo(value: string) {
  const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000));
  if (minutes < 1) return "Vừa xong"; if (minutes < 60) return `${minutes} phút`; if (minutes < 1440) return `${Math.floor(minutes / 60)} giờ`; return `${Math.floor(minutes / 1440)} ngày`;
}

export default function CommunityPage() {
  const [posts, setPosts] = useState<CommunityPost[]>([]); const [user, setUser] = useState<AuthUser | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setPosts(await getCommunityPosts()); } catch { setError("Không tải được bảng tin cộng đồng. Hãy kiểm tra kết nối rồi thử lại."); } finally { setLoading(false); } };
  useEffect(() => { setUser(getAuthUser()); load(); }, []);
  return <main className="min-h-screen px-4 py-8 sm:px-6 lg:py-10"><div className="mx-auto grid max-w-6xl gap-6 lg:grid-cols-[1fr_300px]"><section>
    <div className="mb-6 flex items-end justify-between"><div><div className="eyebrow"><UsersRound className="h-3.5 w-3.5 text-sky-400" /> Community</div><h1 className="mt-2 text-3xl font-semibold text-white">Góc nhìn nhà đầu tư</h1><p className="mt-2 text-sm text-slate-400">Trao đổi về crypto, chứng khoán và các tín hiệu thị trường.</p></div></div>
    {user ? <Composer onCreated={(post) => setPosts((current) => [post, ...current])} /> : <div className="surface mb-5 flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-100">Bạn có góc nhìn muốn chia sẻ?</p><p className="mt-1 text-sm text-slate-400">Đăng nhập để đăng bài, thả tim và bình luận.</p></div><Link href="/login" className="rounded-xl bg-sky-500 px-4 py-2.5 text-center text-sm font-semibold text-slate-950 hover:bg-sky-400">Đăng nhập</Link></div>}
    {error && <div role="alert" className="mb-5 flex items-center justify-between gap-3 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200"><span>{error}</span><button onClick={load} className="shrink-0 rounded-lg border border-red-300/20 px-3 py-1.5 font-medium hover:bg-red-500/10">Thử lại</button></div>}
    {loading ? <div className="grid place-items-center py-20"><Loader2 className="h-7 w-7 animate-spin text-sky-400" /></div> : posts.length ? <div className="space-y-4">{posts.map((post) => <CommunityCard key={post.id} post={post} user={user} />)}</div> : <div className="surface p-10 text-center"><UsersRound className="mx-auto h-8 w-8 text-sky-400" /><p className="mt-4 font-medium text-white">Chưa có thảo luận nào</p><p className="mt-2 text-sm text-slate-400">Hãy mở đầu cuộc trò chuyện đầu tiên của cộng đồng.</p></div>}
  </section><aside className="space-y-4"><div className="surface p-5"><div className="eyebrow"><Sparkles className="h-3.5 w-3.5 text-amber-300" /> Community rules</div><ul className="mt-4 space-y-3 text-sm leading-5 text-slate-400"><li>Chia sẻ luận điểm, không hô hào FOMO.</li><li>Nêu rõ nguồn khi trích dẫn dữ liệu.</li><li>Tôn trọng thành viên và quản trị viên.</li></ul></div><div className="rounded-2xl border border-sky-400/20 bg-sky-500/5 p-5"><p className="text-sm font-semibold text-sky-100">Premium communities</p><p className="mt-2 text-sm leading-6 text-slate-400">Group riêng và phân tích nâng cao sẽ được mở khi hệ thống gói thành viên hoàn thiện.</p></div></aside></div></main>;
}

function Composer({ onCreated }: { onCreated: (post: CommunityPost) => void }) { const [content, setContent] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); async function submit(e: FormEvent) { e.preventDefault(); if (!content.trim()) return; setSaving(true); setError(""); try { const post = await createPost(content.trim()); onCreated(post); setContent(""); } catch (err: any) { setError(err?.response?.data?.message || "Không thể đăng bài lúc này."); } finally { setSaving(false); } } return <form onSubmit={submit} className="surface mb-5 p-4"><textarea value={content} onChange={(e) => setContent(e.target.value)} rows={3} maxLength={3000} placeholder="Bạn đang theo dõi cơ hội hay rủi ro nào?" className="w-full resize-none bg-transparent text-sm leading-6 text-white outline-none placeholder:text-slate-500" />{error && <p className="mt-2 text-xs text-red-300">{error}</p>}<div className="mt-3 flex items-center justify-between border-t border-slate-800 pt-3"><span className="text-xs text-slate-500">{content.length}/3000</span><button disabled={saving || !content.trim()} className="inline-flex items-center gap-2 rounded-lg bg-sky-500 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}Đăng bài</button></div></form>; }

function CommunityCard({ post, user }: { post: CommunityPost; user: AuthUser | null }) { const [likes, setLikes] = useState(0); const [myReaction, setMyReaction] = useState<string | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [open, setOpen] = useState(false); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const [actionError, setActionError] = useState(""); const displayName = user?.id === post.author_id ? user.username : `Nhà đầu tư ${post.author_id.slice(-4)}`;
  useEffect(() => { if (!user) return; Promise.all([getReactions(post.id), getComments(post.id)]).then(([reactionData, commentData]) => { setLikes(reactionData.length); setMyReaction(reactionData.find((item) => item.author_id === user.id)?.id || null); setComments(commentData); }).catch(() => setActionError("Không tải được tương tác của bài viết này.")); }, [post.id, user]);
  async function like() { if (!user) return; setBusy(true); setActionError(""); try { if (myReaction) { await deleteReaction(myReaction); setMyReaction(null); setLikes((x) => Math.max(0, x - 1)); } else { const reaction = await createReaction(post.id); setMyReaction(reaction.id); setLikes((x) => x + 1); } } catch { setActionError("Không thể cập nhật lượt thích. Hãy thử lại."); } finally { setBusy(false); } }
  async function addComment(e: FormEvent) { e.preventDefault(); if (!comment.trim() || !user) return; setBusy(true); setActionError(""); try { const created = await createComment(post.id, comment.trim()); setComments((items) => [...items, created]); setComment(""); } catch { setActionError("Không thể gửi bình luận. Hãy thử lại."); } finally { setBusy(false); } }
  async function share() { await navigator.clipboard?.writeText(`${window.location.origin}/community#${post.id}`); }
  return <article id={post.id} className="surface p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-sky-500/15 font-semibold text-sky-300">{displayName.slice(0, 1).toUpperCase()}</div><div><p className="text-sm font-semibold text-slate-100">{displayName}</p><p className="mt-0.5 text-xs text-slate-500">{timeAgo(post.created_at)} · Công khai</p></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-300">{post.content}</p>{actionError && <p role="alert" className="mt-3 text-xs text-red-300">{actionError}</p>}<div className="mt-4 flex items-center gap-2 border-t border-slate-800 pt-3"><button onClick={like} disabled={busy || !user} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm transition ${myReaction ? "bg-rose-500/10 text-rose-300" : "text-slate-400 hover:bg-slate-900 hover:text-slate-200"}`}><Heart className={`h-4 w-4 ${myReaction ? "fill-current" : ""}`} />{likes || "Thích"}</button><button onClick={() => setOpen(!open)} className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-slate-400 hover:bg-slate-900 hover:text-slate-200"><MessageCircle className="h-4 w-4" />{comments.length || "Bình luận"}</button><button onClick={share} className="ml-auto rounded-lg p-2 text-slate-500 hover:bg-slate-900 hover:text-slate-200" aria-label="Chia sẻ"><Share2 className="h-4 w-4" /></button></div>{open && <div className="mt-4 border-t border-slate-800 pt-4"><div className="space-y-3">{comments.map((item) => <div key={item.id} className="rounded-xl bg-slate-900/70 p-3 text-sm"><span className="font-medium text-slate-200">Nhà đầu tư {item.author_id.slice(-4)}</span><p className="mt-1 text-slate-400">{item.content}</p></div>)}</div>{user ? <form onSubmit={addComment} className="mt-3 flex gap-2"><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Viết bình luận..." className="min-w-0 flex-1 rounded-lg border border-slate-800 bg-slate-900 px-3 py-2 text-sm text-white outline-none focus:border-sky-400" /><button disabled={busy || !comment.trim()} className="rounded-lg bg-sky-500 px-3 text-slate-950 disabled:opacity-50"><Send className="h-4 w-4" /></button></form> : <p className="mt-3 text-sm text-slate-500">Đăng nhập để tham gia thảo luận.</p>}</div>}</article>; }
