"use client";

import Link from "next/link";
import { notFound } from "next/navigation";
import { use } from "react";
import { ShieldCheck } from "lucide-react";
import { translate, useLanguage } from "@/context/LanguageContext";

type Copy = [string, string];
type InfoPage = { title: Copy; intro: Copy; sections: Array<{ heading: Copy; body: Copy }> };

const pages: Record<string, InfoPage> = {
  about: { title: ["Về CryptoCheck", "About CryptoCheck"], intro: ["CryptoCheck giúp người dùng đặt dữ liệu thị trường và phạm vi kiểm tra token vào đúng ngữ cảnh trước khi ra quyết định.", "CryptoCheck helps users place market data and token inspection scope in the right context before making decisions."], sections: [{ heading: ["Mục tiêu", "Our goal"], body: ["Cung cấp thông tin rõ ràng, có nguồn và dễ kiểm chứng cho cộng đồng crypto. Kết quả tự động không thay thế audit, tư vấn đầu tư hoặc thẩm định độc lập.", "Provide clear, sourced and verifiable information for the crypto community. Automated results do not replace an audit, investment advice or independent due diligence."] }, { heading: ["Nền tảng làm gì", "What the platform does"], body: ["Bạn có thể theo dõi thị trường, đọc tin tổng hợp, tham gia cộng đồng và xem phạm vi dữ liệu công khai mà một lượt quét token có thể kiểm tra.", "You can follow markets, read aggregated news, join the community and view the public-data scope a token inspection can check."] }] },
  roadmap: { title: ["Lộ trình phát triển", "Product roadmap"], intro: ["Lộ trình được cập nhật theo các hạng mục đã kiểm thử; chúng tôi không xem ý tưởng hay giao diện mẫu là tính năng đã phát hành.", "The roadmap is updated only for verified work; we do not treat an idea or a UI mockup as a shipped feature."], sections: [{ heading: ["Đang hoàn thiện", "In progress"], body: ["Cải thiện trải nghiệm social, kiểm thử responsive/a11y, mở rộng phạm vi scanner một cách minh bạch và hoàn thiện quan sát lỗi production.", "Improving social UX, responsive/a11y testing, transparently broadening scanner scope and completing production observability."] }, { heading: ["Premium", "Premium"], body: ["Tính năng Premium chỉ được mở khi entitlement phía máy chủ xác nhận. Checkout chỉ xuất hiện sau khi luồng thanh toán và webhook hoàn chỉnh.", "Premium features unlock only when server-side entitlement confirms them. Checkout appears only after the payment and webhook flow is complete."] }] },
  contact: { title: ["Liên hệ", "Contact"], intro: ["Kênh liên hệ công khai đang được cấu hình. Không gửi khoá ví, mật khẩu, seed phrase hoặc thông tin thanh toán qua bất kỳ kênh nào.", "Public contact channels are being configured. Never send wallet keys, passwords, seed phrases or payment details through any channel."], sections: [{ heading: ["Báo lỗi", "Report an issue"], body: ["Khi một yêu cầu API lỗi, hãy gửi thời điểm xảy ra lỗi, thao tác đã thực hiện và mã request_id (nếu có). Điều này giúp đội ngũ lần trace nhanh hơn.", "When an API request fails, share the time, the action you took and the request_id (if shown). This helps the team trace it faster."] }, { heading: ["Hợp tác", "Partnerships"], body: ["Thông tin liên hệ cho quảng cáo và hợp tác sẽ được công bố tại đây khi kênh chính thức sẵn sàng.", "Advertising and partnership contact details will be published here once an official channel is ready."] }] },
  terms: { title: ["Điều khoản sử dụng", "Terms of use"], intro: ["CryptoCheck cung cấp công cụ và dữ liệu tham khảo, không phải tư vấn đầu tư, pháp lý hay cam kết an toàn của bất kỳ token nào.", "CryptoCheck provides reference tools and data. It is not investment or legal advice, nor a safety guarantee for any token."], sections: [{ heading: ["Quyết định đầu tư", "Investment decisions"], body: ["Bạn chịu trách nhiệm tự xác minh nguồn, contract, thanh khoản và rủi ro trước mọi quyết định giao dịch.", "You remain responsible for verifying sources, contracts, liquidity and risks before every trading decision."] }, { heading: ["Nội dung cộng đồng", "Community content"], body: ["Người dùng chịu trách nhiệm về nội dung họ đăng. Nội dung vi phạm pháp luật, mạo danh, lừa đảo hoặc gây hại có thể bị gỡ theo chính sách vận hành.", "Users are responsible for what they publish. Illegal, impersonating, fraudulent or harmful content may be removed under operational policy."] }] },
  privacy: { title: ["Chính sách bảo mật", "Privacy policy"], intro: ["Chúng tôi chỉ sử dụng dữ liệu cần thiết để vận hành tài khoản, cộng đồng và các yêu cầu của bạn.", "We use only the data needed to operate accounts, community features and your requests."], sections: [{ heading: ["Tài khoản", "Accounts"], body: ["Thông tin đăng ký và trạng thái phiên được dùng để xác thực những chức năng yêu cầu đăng nhập. Không bao giờ nhập seed phrase hoặc private key vào CryptoCheck.", "Registration information and session state are used to authenticate sign-in-only features. Never enter a seed phrase or private key into CryptoCheck."] }, { heading: ["Dữ liệu công khai", "Public data"], body: ["Dữ liệu thị trường, explorer và bài viết từ nguồn bên ngoài có thể được hiển thị kèm nguồn; tính sẵn có phụ thuộc nhà cung cấp tương ứng.", "Market, explorer and external-article data may be displayed with source attribution; availability depends on each provider."] }] },
  faq: { title: ["Câu hỏi thường gặp", "Frequently asked questions"], intro: ["Một vài điều quan trọng trước khi dùng CryptoCheck.", "A few important things to know before using CryptoCheck."], sections: [{ heading: ["Scanner có phải audit không?", "Is the scanner an audit?"], body: ["Không. Scanner chỉ tổng hợp phạm vi dữ liệu công khai và các tín hiệu tự động. Kết quả không chứng nhận token an toàn và không thể thay thế audit chuyên nghiệp.", "No. The scanner aggregates public-data scope and automated signals. Results do not certify a token as safe and cannot replace a professional audit."] }, { heading: ["Vì sao có nhiều token trùng tên?", "Why are there multiple tokens with the same name?"], body: ["Symbol không phải mã định danh duy nhất. Hãy chọn theo chain, địa chỉ contract/mint, logo, thanh khoản, giá và volume trước khi quét.", "A symbol is not a unique identifier. Choose by chain, contract/mint address, logo, liquidity, price and volume before scanning."] }, { heading: ["Premium hoạt động thế nào?", "How does Premium work?"], body: ["Quyền Premium do API xác nhận. Giao diện không tự cấp quyền; khi thanh toán chính thức sẵn sàng, trạng thái sẽ được đồng bộ từ máy chủ.", "Premium access is confirmed by the API. The interface never grants it on its own; once official payments are available, status will sync from the server."] }] },
};

export default function InfoPageRoute({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params);
  const page = pages[slug];
  const { language } = useLanguage();
  if (!page) notFound();
  const text = (copy: Copy) => translate(language, copy[0], copy[1]);
  return <main id="main-content" className="min-h-[70vh] bg-[#050505] px-4 py-14 text-slate-100 sm:px-6"><article className="mx-auto max-w-3xl rounded-2xl border border-slate-800 bg-slate-950/70 p-6 shadow-2xl shadow-black/20 sm:p-10"><div className="mb-7 flex items-center gap-3 text-sky-300"><span className="grid h-10 w-10 place-items-center rounded-xl border border-sky-400/25 bg-sky-400/10"><ShieldCheck className="h-5 w-5" /></span><span className="text-sm font-semibold tracking-wide">CryptoCheck</span></div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{text(page.title)}</h1><p className="mt-4 text-base leading-7 text-slate-300">{text(page.intro)}</p><div className="mt-9 space-y-7">{page.sections.map((section) => <section key={section.heading[0]}><h2 className="text-lg font-semibold text-slate-100">{text(section.heading)}</h2><p className="mt-2 leading-7 text-slate-300">{text(section.body)}</p></section>)}</div><Link href="/" className="mt-10 inline-flex rounded-lg border border-sky-400/30 px-4 py-2 text-sm font-semibold text-sky-200 transition hover:bg-sky-400/10">{translate(language, "Về trang chủ", "Back to home")}</Link></article></main>;
}
